-- =============================================
-- TABLAS DE GEOGRAFÍA PARA VENEZUELA
-- =============================================

CREATE TABLE estados (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE municipios (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    estado_id INT NOT NULL REFERENCES estados(id)
);

CREATE TABLE parroquias (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    municipio_id INT NOT NULL REFERENCES municipios(id)
);

CREATE TABLE comunas (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    municipio_id INT NOT NULL REFERENCES municipios(id)
);

-- =============================================
-- DATOS: ESTADO
-- =============================================
INSERT INTO estados (id, nombre) VALUES (1, 'NUEVA ESPARTA');

-- =============================================
-- DATOS: MUNICIPIOS
-- =============================================
INSERT INTO municipios (id, nombre, estado_id) VALUES
(1, 'ARISMENDI', 1),
(2, 'DÍAZ', 1),
(3, 'GÓMEZ', 1),
(4, 'MANEIRO', 1),
(5, 'MARCANO', 1),
(6, 'MARIÑO', 1),
(7, 'PENÍNSULA DE MACANAO', 1),
(8, 'VILLALBA', 1),
(9, 'TUBORES', 1),
(10, 'ANTOLÍN DEL CAMPO', 1),
(11, 'GARCÍA', 1);

-- =============================================
-- DATOS: PARROQUIAS
-- =============================================
INSERT INTO parroquias (id, nombre, municipio_id) VALUES
(1, 'LA ASUNCIÓN', 1),
(2, 'SAN JUAN BAUTISTA', 2),
(3, 'ZABALA', 2),
(4, 'SANTA ANA', 3),
(5, 'GUEVARA', 3),
(6, 'MATASIETE', 3),
(7, 'BOLÍVAR', 3),
(8, 'SUCRE', 3),
(9, 'PAMPATAR', 4),
(10, 'AGUIRRE', 4),
(11, 'JUAN GRIEGO', 5),
(12, 'ADRIÁN', 5),
(13, 'PORLAMAR', 6),
(14, 'BOCA DEL RÍO', 7),
(15, 'SAN FRANCISCO', 7),
(16, 'SAN PEDRO DE COCHE', 8),
(17, 'VICENTE FUENTES', 8),
(18, 'PUNTA DE PIEDRAS', 9),
(19, 'LOS BARALES', 9),
(20, 'LA PLAZA DE PARAGUACHI', 10),
(21, 'VALLE ESP SANTO', 11),
(22, 'FRANCISCO FAJARDO', 11);

-- =============================================
-- DATOS: COMUNAS
-- =============================================
INSERT INTO comunas (id, nombre, municipio_id) VALUES
-- ARISMENDI (ID 1)
(1, 'COMUNA SOCIALISTA AGRO-TURÍSTICA GUAYATAMO', 1),
(2, 'AGROTURÍSTICA Y PRODUCTIVA BATALLA DE MATASIETE', 1),
(3, 'CIRCUITO #8 VALLE DE SANTA LUCIA', 1),
(4, 'EL FORTÍN DE LA LIBERTAD', 1),
(5, 'AGROECOLÓGICA PRODUCTIVA MANANTIAL DE LA RESISTENCIA', 1),
-- DÍAZ (ID 2)
(6, 'EL VALLE DE SAN JUAN', 2),
(7, 'CERRO PURULÚ', 2),
(8, 'NUESTRA PALMA DATILERA', 2),
(9, 'SOCIOPRODUCTIVA EL DATIL', 2),
(10, 'SUR DE DÍAZ', 2),
(11, 'LAGUNA LAS MARITES', 2),
(12, 'MAR BENDITO', 2),
(13, 'UNIÓN DE LAS GUEVARAS', 2),
(14, 'MARÍA AUXILIADORA', 2),
(15, 'BUFADERO', 2),
-- GÓMEZ (ID 3)
(16, 'VILLA SANTA ANA DEL NORTE', 3),
(17, 'EL PUEBLO DE LA HAMACA', 3),
(18, 'LA VECINDAD SOCIALISTA', 3),
(19, 'TACARIGUA UNIDA', 3),
(20, 'CIRCUITO # 10 PEDRO GONZÁLEZ', 3),
(21, 'UNIDOS COMO ARTESANAS', 3),
(22, 'SOCIALISTA BRISAS DEL CARIBE', 3),
(23, 'SOCIALISTA LOS HATOS DE ALTAGRACIA', 3),
-- MANEIRO (ID 4)
(24, 'ANACLETA LABORY', 4),
(25, 'SEMBRANDO PATRIA', 4),
(26, 'EL GUANAGUANARE', 4),
(27, 'LA CAYENA', 4),
-- MARCANO (ID 5)
(28, 'HÉROES DE LA LAGUNA DE LOS MÁRTIRES', 5),
(29, 'SOCIALISTA LAS SALINAS DE JUANGRIEGO', 5),
(30, 'HEROÍNAS DE LA SABANETA', 5),
(31, 'RENACER SOCIALISTA DE LOS MILLANES', 5),
(32, 'LAS VICUNAS', 5),
(33, 'ALBERTO LOVERA', 5),
-- MARIÑO (ID 6)
(34, 'CACICA ISABEL', 6),
(35, 'MARÍA LEÓN LA LEONA DE CHÁVEZ', 6),
(36, 'CHOTOMAYMU TIERRA FÉRTIL', 6),
(37, 'PESQUERA GUAIQUERÍ', 6),
(38, 'FORJADORES DE LA PATRIA NUEVA', 6),
(39, 'GENERAL EN JEFE SANTIAGO MARIÑO', 6),
(40, 'PRODUCCIÓN BRISAS DEL MAR', 6),
(41, 'VISTA AL MAR LA PERLA DEL CARIBE', 6),
(42, 'CAMARADA ROBERTO CABELLO', 6),
(43, 'ROSA INÉS', 6),
(44, 'WAIKERI CHARAIMA', 6),
(45, 'CIUDAD MARINERA', 6),
(46, 'CIRCUITO #13 LA AUYAMA', 6),
(47, 'GENERAL EN JEFE JOSÉ ASCUNCIÓN RODRÍGUEZ', 6),
-- PENÍNSULA DE MACANAO (ID 7)
(48, 'SAN FRANCISCO DE ASÍS', 7),
(49, 'SOCIALISTA AGROPESQUERA VIRGEN DE COROMOTO', 7),
(50, 'CIRCUITO COMUNAL GUAYANCANCITO', 7),
(51, 'CIRCUITO COMUNAL SIMÓN BOLÍVAR', 7),
(52, 'ROBLEPOZO', 7),
(53, 'COMUNA PESQUERA SAN ANTONIO DE PADUA', 7),
-- VILLALBA (ID 8)
(54, 'TURÍSTICA PESQUERA COMANDANTE FELIPE VILLALBA', 8),
(55, 'VICENTE FUENTES', 8),
-- TUBORES (ID 9)
(56, 'CORONEL JOSÉ CELEDONIO TUBORES', 9),
(57, 'ECO-COMUNA LA RESTINGA', 9),
(58, 'BOLIVARIANA PUNTA DE PIEDRA HEROICA', 9),
(59, 'EL ÁGUILA BLANCA DEL JARDÍN', 9),
(60, 'LOS PUEBLOS DE MARÍA GUEVARA', 9),
(61, 'BOLIVARIANA CAMARADA GIL BELLO', 9),
(62, 'BATALLA DE LOS BARALES', 9),
-- ANTOLÍN DEL CAMPO (ID 10)
(63, 'AL PIE DEL GUAYAMURI', 10),
(64, 'PESQUERA AGRO-TURÍSTICA EL TIRANO - EL CARDÓN', 10),
(65, 'AGRO-TURÍSTICA Y PESQUERA MANZANILLO', 10),
(66, 'SOCIALISTA, AGROTURÍSTICA Y PRODUCTIVA, ENTRE ARICAGUA, EL AGUA Y LA MIRA JAMÁS SERÁ VENCIDA', 10),
(67, 'COMUNA SOCIALISTA Y PRODUCTIVA ENTRE MONTAÑAS SOBERANAS', 10),
-- GARCÍA (ID 11)
(68, 'CHARAGUARAY', 11),
(69, 'SOCIALISTA SAN ANTONIO', 11),
(70, 'VILLA ROSA', 11),
(71, 'SOCIALISTA VILLA JUANA', 11),
(72, 'CIRCUITO 6 VALLE VERDE', 11),
(73, 'EL MANGLAR DE LAS 4 LUNAS', 11),
(74, 'CRUZ DEL PASTEL', 11),
(75, 'LAS MARIITAS', 11);

-- Índices
CREATE INDEX idx_municipios_estado ON municipios(estado_id);
CREATE INDEX idx_parroquias_municipio ON parroquias(municipio_id);
CREATE INDEX idx_comunas_municipio ON comunas(municipio_id);